CREATE TABLE IF NOT EXISTS `users`(
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(30) NOT NULL UNIQUE,
	`password` VARCHAR(64) NOT NULL,
	`createAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updateAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE user ADD avatar_url VARCHAR(200);

SELECT * FROM avatar WHERE user_id = 1 ORDER BY createAt DESC LIMIT 0,1;